import React from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';

const Home = () => {
  const navigate = useNavigate();

  return (
    <div className="home-premium">
      {/* Overlay top-nav shadow (optional but good for depth) */}
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '1px', background: 'var(--border2)' }} />

      <div className="home-hero-content">
        <motion.div 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }} 
          transition={{ duration: 0.6 }}
          className="hero-badge"
          style={{ padding: '0.4rem 1rem', fontSize: '0.8rem', background: 'rgba(34,211,238,0.1)', borderColor: 'rgba(34,211,238,0.3)', color: 'var(--accent2)', marginBottom: '1.5rem' }}
        >
          <span className="pulse-dot" style={{ background: 'var(--accent2)' }}></span>
          V7 Intelligence Engine Active
        </motion.div>

        <motion.h1 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }} 
          transition={{ duration: 0.6, delay: 0.1 }}
          className="home-hero-title"
        >
          <span className="home-txt-gradient">Architect Your </span>
          <span className="home-txt-accent">Career Path</span><br/>
          <span className="home-txt-gradient">With AI Precision</span>
        </motion.h1>

        <motion.p 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }} 
          transition={{ duration: 0.6, delay: 0.2 }}
          className="home-hero-subtitle"
        >
          Unlock an intelligent roadmap generated by analyzing 225+ industry roles, 18,000+ degree-mappings, and real-time market viability data in just 6 simple steps.
        </motion.p>
        
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }} 
          animate={{ opacity: 1, scale: 1 }} 
          transition={{ duration: 0.5, delay: 0.4 }}
          className="home-btn-group"
        >
          <button className="btn-premium" onClick={() => navigate('/onboarding')}>
            Start My Analysis ✨
          </button>
          <button className="btn-premium-ghost" onClick={() => navigate('/login')}>
            Sign In to Dashboard →
          </button>
        </motion.div>
      </div>

      <motion.div 
        initial={{ opacity: 0, y: 40 }} 
        animate={{ opacity: 1, y: 0 }} 
        transition={{ duration: 0.8, delay: 0.5 }}
        className="home-feature-grid"
      >
        <div className="home-glass-card">
          <div className="hgc-icon">📈</div>
          <h3 className="hgc-title">Real-Time Market Data</h3>
          <p className="hgc-desc">
            We map your skills against live vacancy rates and competitive salary brackets across top global tech hubs.
          </p>
        </div>

        <div className="home-glass-card" style={{ transform: 'translateY(-15px)' }}>
          <div className="hgc-icon">🤖</div>
          <h3 className="hgc-title">ML Success Prediction</h3>
          <p className="hgc-desc">
            Our proprietary matching engine evaluates your academic and personal background to predict role success odds.
          </p>
        </div>

        <div className="home-glass-card">
          <div className="hgc-icon">🗺️</div>
          <h3 className="hgc-title">Holistic 3-Path Roadmap</h3>
          <p className="hgc-desc">
            We don't just give one path. Get customized upskilling roadmaps for your Primary, Alternative, and Tertiary career goals.
          </p>
        </div>
      </motion.div>
    </div>
  );
};

export default Home;
